name: sidecar
services:
  proxy:
    image: nginx
    volumes:
      - ./compose/proxy/conf:/etc/nginx/conf.d
    ports:
      - "7982:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - app
    links:
      - app
      - api

  app:
    build:
      context: .
      args:
        RELOAD: "--reload"
    volumes:
      - ./src:/app/src
    depends_on:
      - api
    links:
      - api

  api:
    build: ./compose/api/
    volumes:
      - ./compose/api/data:/app/data
