name: canary
services:
  proxy:
    image: nginx
    volumes:
      - ./compose/proxy/conf:/etc/nginx/conf.d
    ports:
      - "7942:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - app
    links:
      - app
      - api

  app:
    build:
      context: .
    platform: linux/amd64
    args:
      MODE: compose
    depends_on:
      - api
    links:
      - api

  api:
    build: ./compose/api/
    volumes:
      - ./compose/api/data:/app/data
    ports:
      - "8949:80"


